source 'https://github.com/WyICSP/WFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!                         #去除警告
target 'WFApplyArea_Example' do
  pod 'WFApplyArea', :path => '../'

  target 'WFApplyArea_Tests' do
    inherit! :search_paths

    
  end
end
